app:
  name: ui
  image:
    repository: onecx/onecx-ai-provider-ui
  routing:
    enabled: true
    path: /mfe/onecxAiUiProvider/
  operator:
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: ./OnecxAiUiProviderModule
          description: OneCX OnecxAiUi Provider Module
          note: OneCX OnecxAiUi Provider UI module auto import via MF operator
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: onecx-ai-provider-ui
          tagName: onecx-ai-provider-ui-webcomponent
    permission:
      enabled: true
      spec:
        permissions:
          PROVIDER:
            CREATE: Create Provider
            EDIT: Edit Provider
            DELETE: Delete Provider
            SAVE: Update and save Provider
            IMPORT: Import Provider
            EXPORT: Export Provider
            VIEW: View mode for Provider
            SEARCH: Search Provider
            CHANGE_API_KEY: Change ApiKey Provider
          CONFIGURATION:
            CREATE: Create configuration
            EDIT: Edit configuration
            DELETE: Delete configuration
            SAVE: Update and save configuration
            IMPORT: Import configuration
            EXPORT: Export configuration
            VIEW: View mode for configuration
            SEARCH: Search configuration
            BACK: Back to configuration
          MCPSERVER:
            CREATE: Create mcpserver
            EDIT: Edit mcpserver
            DELETE: Delete mcpserver
            SAVE: Update and save mcpserver
            IMPORT: Import mcpserver
            EXPORT: Export mcpserver
            VIEW: View mode for mcpserver
            SEARCH: Search mcpserver
            BACK: Navigate back in details of mcpserver
          DASHBOARD:
            CREATE: Create Dashboard item
            EDIT: Edit Dashboard item
            DELETE: Delete Dashboard item
            SEARCH: Search Dashboard items
            VIEW: View Dashboard item details
            IMPORT: Import Dashboard items
            EXPORT: Export Dashboard items
            BACK: Navigate back in details of Dashboard item
          AGENT:
            CREATE: Create Agent item
            EDIT: Edit Agent item
            DELETE: Delete Agent item
            SEARCH: Search Agent items
            VIEW: View Agent item details
            IMPORT: Import Agent items
            EXPORT: Export Agent items
            BACK: Navigate back in details of Agent item
          SCAFFOLD:
            CREATE: Create Scaffold item
            EDIT: Edit Scaffold item
            DELETE: Delete Scaffold item
            SEARCH: Search Scaffold items
            VIEW: View Scaffold item details
            IMPORT: Import Scaffold items
            EXPORT: Export Scaffold items
            BACK: Navigate back in details of Scaffold item
          SKILL:
            CREATE: Create Skill item
            EDIT: Edit Skill item
            DELETE: Delete Skill item
            SEARCH: Search Skill items
            VIEW: View Skill item details
            IMPORT: Import Skill items
            EXPORT: Export Skill items
            BACK: Navigate back in details of Skill item
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-ai-provider-ui
